name: Publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # Matches semantic versioning tags like v1.0.0, v2.1.3, etc..

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'  # Use the latest LTS version
          cache: 'npm'  # Cache npm dependencies

      - name: Install dependencies
        run: npm ci  # Faster and cleaner dependency installation

      # - name: Lint code
      #   run: npm run lint  # Run linter (e.g., ESLint)

      # - name: Check formatting
      #   run: npm run format:check  # Verify code formatting (e.g., Prettier)

      - name: Build project
        run: npm run build

      # - name: Check types
      #   run: npm run type-check  # Type-check with TypeScript if applicable

      - name: Run security audit
        run: npm audit --audit-level=critical  # Focus on critical vulnerabilities

      # - name: Run tests
      #   run: npm run test -- --coverage  # Run tests with coverage report

      - name: Publish to NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release



# name: Publish
# on:
#   push:
#     branches:
#       - main

# permissions:
#   contents: write
#   packages: write
#   pull-requests: write     

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#         - uses: actions/checkout@v4
#         - uses: actions/setup-node@v4
#           with:
#             node-version: 'lts/*'
#         - run: npm ci
#         - run: npm run build
#         - run: npm audit signature
#         # - run: npm run test
#         - name: Publish to NPM
#           env:
#             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#             NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#           run: npx semantic-release
  